# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow_02.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow_02(object):
    def setupUi(self, OtherWindow_02):
        OtherWindow_02.setObjectName("OtherWindow_02")
        OtherWindow_02.resize(138, 200)
        OtherWindow_02.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(OtherWindow_02)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        OtherWindow_02.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow_02)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 138, 21))
        self.menubar.setObjectName("menubar")
        OtherWindow_02.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow_02)
        self.statusbar.setObjectName("statusbar")
        OtherWindow_02.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow_02)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow_02)

    def retranslateUi(self, OtherWindow_02):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow_02.setWindowTitle(_translate("OtherWindow_02", "Productos"))
        self.label.setText(_translate("OtherWindow_02", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">- Programa 01</span></p><p align=\"center\"><span style=\" font-size:14pt;\">- Programa 02</span></p><p align=\"center\"><span style=\" font-size:14pt;\">- Programa 03</span></p><p align=\"center\"><span style=\" font-size:14pt;\">- Programa 04</span><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow_02 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow_02()
    ui.setupUi(OtherWindow_02)
    OtherWindow_02.show()
    sys.exit(app.exec_())
