# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow_01(object):
    def setupUi(self, OtherWindow_01):
        OtherWindow_01.setObjectName("OtherWindow_01")
        OtherWindow_01.resize(367, 219)
        OtherWindow_01.setStyleSheet("background-color: rgb(15, 72, 115);")
        self.centralwidget = QtWidgets.QWidget(OtherWindow_01)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HACKED")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        OtherWindow_01.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow_01)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 21))
        self.menubar.setObjectName("menubar")
        OtherWindow_01.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow_01)
        self.statusbar.setObjectName("statusbar")
        OtherWindow_01.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow_01)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow_01)

    def retranslateUi(self, OtherWindow_01):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow_01.setWindowTitle(_translate("OtherWindow_01", "Síguenos!"))
        self.label.setText(_translate("OtherWindow_01", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#ffffff;\">TW</span></p></body></html>"))
