# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option04_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_23.addWidget(self.label_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mdiArea = QtWidgets.QMdiArea(self.tab)
        self.mdiArea.setMinimumSize(QtCore.QSize(200, 200))
        self.mdiArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mdiArea.setStyleSheet("background-color: rgb(0, 170, 255);")
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.gridLayout = QtWidgets.QGridLayout(self.subwindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.subwindow)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.subwindow)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.subwindow)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_18 = QtWidgets.QLabel(self.subwindow)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.subwindow)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.subwindow)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.subwindow)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.subwindow)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.subwindow)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_Jan_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila01.setObjectName("lineEdit_Jan_Fila01")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila01)
        self.lineEdit_Jan_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila02.setObjectName("lineEdit_Jan_Fila02")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila02)
        self.lineEdit_Jan_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila03.setObjectName("lineEdit_Jan_Fila03")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila03)
        self.lineEdit_Jan_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila04.setObjectName("lineEdit_Jan_Fila04")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila04)
        self.lineEdit_Jan_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila05.setObjectName("lineEdit_Jan_Fila05")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila05)
        self.lineEdit_Jan_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila06.setObjectName("lineEdit_Jan_Fila06")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila06)
        self.lineEdit_Jan_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila07.setObjectName("lineEdit_Jan_Fila07")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.subwindow)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_Feb_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila01.setObjectName("lineEdit_Feb_Fila01")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila01)
        self.lineEdit_Feb_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila02.setObjectName("lineEdit_Feb_Fila02")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila02)
        self.lineEdit_Feb_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila03.setObjectName("lineEdit_Feb_Fila03")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila03)
        self.lineEdit_Feb_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila04.setObjectName("lineEdit_Feb_Fila04")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila04)
        self.lineEdit_Feb_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila05.setObjectName("lineEdit_Feb_Fila05")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila05)
        self.lineEdit_Feb_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila06.setObjectName("lineEdit_Feb_Fila06")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila06)
        self.lineEdit_Feb_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila07.setObjectName("lineEdit_Feb_Fila07")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.subwindow)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.lineEdit_Mar_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila01.setObjectName("lineEdit_Mar_Fila01")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila01)
        self.lineEdit_Mar_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila02.setObjectName("lineEdit_Mar_Fila02")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila02)
        self.lineEdit_Mar_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila03.setObjectName("lineEdit_Mar_Fila03")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila03)
        self.lineEdit_Mar_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila04.setObjectName("lineEdit_Mar_Fila04")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila04)
        self.lineEdit_Mar_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila05.setObjectName("lineEdit_Mar_Fila05")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila05)
        self.lineEdit_Mar_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila06.setObjectName("lineEdit_Mar_Fila06")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila06)
        self.lineEdit_Mar_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila07.setObjectName("lineEdit_Mar_Fila07")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.subwindow)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_Abr_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila01.setObjectName("lineEdit_Abr_Fila01")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila01)
        self.lineEdit_Abr_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila02.setObjectName("lineEdit_Abr_Fila02")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila02)
        self.lineEdit_Abr_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila03.setObjectName("lineEdit_Abr_Fila03")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila03)
        self.lineEdit_Abr_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila04.setObjectName("lineEdit_Abr_Fila04")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila04)
        self.lineEdit_Abr_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila05.setObjectName("lineEdit_Abr_Fila05")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila05)
        self.lineEdit_Abr_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila06.setObjectName("lineEdit_Abr_Fila06")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila06)
        self.lineEdit_Abr_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila07.setObjectName("lineEdit_Abr_Fila07")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.subwindow)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEdit_May_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila01.setObjectName("lineEdit_May_Fila01")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila01)
        self.lineEdit_May_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila02.setObjectName("lineEdit_May_Fila02")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila02)
        self.lineEdit_May_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila03.setObjectName("lineEdit_May_Fila03")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila03)
        self.lineEdit_May_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila04.setObjectName("lineEdit_May_Fila04")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila04)
        self.lineEdit_May_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila05.setObjectName("lineEdit_May_Fila05")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila05)
        self.lineEdit_May_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila06.setObjectName("lineEdit_May_Fila06")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila06)
        self.lineEdit_May_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila07.setObjectName("lineEdit_May_Fila07")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.subwindow)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_Jun_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila01.setObjectName("lineEdit_Jun_Fila01")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila01)
        self.lineEdit_Jun_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila02.setObjectName("lineEdit_Jun_Fila02")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila02)
        self.lineEdit_Jun_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila03.setObjectName("lineEdit_Jun_Fila03")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila03)
        self.lineEdit_Jun_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila04.setObjectName("lineEdit_Jun_Fila04")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila04)
        self.lineEdit_Jun_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila05.setObjectName("lineEdit_Jun_Fila05")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila05)
        self.lineEdit_Jun_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila06.setObjectName("lineEdit_Jun_Fila06")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila06)
        self.lineEdit_Jun_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila07.setObjectName("lineEdit_Jun_Fila07")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.subwindow)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEdit_Jul_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila01.setObjectName("lineEdit_Jul_Fila01")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila01)
        self.lineEdit_Jul_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila02.setObjectName("lineEdit_Jul_Fila02")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila02)
        self.lineEdit_Jul_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila03.setObjectName("lineEdit_Jul_Fila03")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila03)
        self.lineEdit_Jul_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila04.setObjectName("lineEdit_Jul_Fila04")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila04)
        self.lineEdit_Jul_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila05.setObjectName("lineEdit_Jul_Fila05")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila05)
        self.lineEdit_Jul_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila06.setObjectName("lineEdit_Jul_Fila06")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila06)
        self.lineEdit_Jul_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila07.setObjectName("lineEdit_Jul_Fila07")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.subwindow)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.lineEdit_Aug_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila01.setObjectName("lineEdit_Aug_Fila01")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila01)
        self.lineEdit_Aug_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila02.setObjectName("lineEdit_Aug_Fila02")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila02)
        self.lineEdit_Aug_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila03.setObjectName("lineEdit_Aug_Fila03")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila03)
        self.lineEdit_Aug_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila04.setObjectName("lineEdit_Aug_Fila04")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila04)
        self.lineEdit_Aug_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila05.setObjectName("lineEdit_Aug_Fila05")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila05)
        self.lineEdit_Aug_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila06.setObjectName("lineEdit_Aug_Fila06")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila06)
        self.lineEdit_Aug_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila07.setObjectName("lineEdit_Aug_Fila07")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.subwindow)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.lineEdit_Set_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila01.setObjectName("lineEdit_Set_Fila01")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila01)
        self.lineEdit_Set_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila02.setObjectName("lineEdit_Set_Fila02")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila02)
        self.lineEdit_Set_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila03.setObjectName("lineEdit_Set_Fila03")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila03)
        self.lineEdit_Set_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila04.setObjectName("lineEdit_Set_Fila04")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila04)
        self.lineEdit_Set_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila05.setObjectName("lineEdit_Set_Fila05")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila05)
        self.lineEdit_Set_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila06.setObjectName("lineEdit_Set_Fila06")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila06)
        self.lineEdit_Set_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila07.setObjectName("lineEdit_Set_Fila07")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.subwindow)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.lineEdit_Oct_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila01.setObjectName("lineEdit_Oct_Fila01")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila01)
        self.lineEdit_Oct_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila02.setObjectName("lineEdit_Oct_Fila02")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila02)
        self.lineEdit_Oct_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila03.setObjectName("lineEdit_Oct_Fila03")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila03)
        self.lineEdit_Oct_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila04.setObjectName("lineEdit_Oct_Fila04")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila04)
        self.lineEdit_Oct_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila05.setObjectName("lineEdit_Oct_Fila05")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila05)
        self.lineEdit_Oct_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila06.setObjectName("lineEdit_Oct_Fila06")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila06)
        self.lineEdit_Oct_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila07.setObjectName("lineEdit_Oct_Fila07")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.subwindow)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.lineEdit_Nov_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila01.setObjectName("lineEdit_Nov_Fila01")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila01)
        self.lineEdit_Nov_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila02.setObjectName("lineEdit_Nov_Fila02")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila02)
        self.lineEdit_Nov_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila03.setObjectName("lineEdit_Nov_Fila03")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila03)
        self.lineEdit_Nov_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila04.setObjectName("lineEdit_Nov_Fila04")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila04)
        self.lineEdit_Nov_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila05.setObjectName("lineEdit_Nov_Fila05")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila05)
        self.lineEdit_Nov_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila06.setObjectName("lineEdit_Nov_Fila06")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila06)
        self.lineEdit_Nov_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila07.setObjectName("lineEdit_Nov_Fila07")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.subwindow)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.lineEdit_Dic_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila01.setObjectName("lineEdit_Dic_Fila01")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila01)
        self.lineEdit_Dic_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila02.setObjectName("lineEdit_Dic_Fila02")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila02)
        self.lineEdit_Dic_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila03.setObjectName("lineEdit_Dic_Fila03")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila03)
        self.lineEdit_Dic_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila04.setObjectName("lineEdit_Dic_Fila04")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila04)
        self.lineEdit_Dic_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila05.setObjectName("lineEdit_Dic_Fila05")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila05)
        self.lineEdit_Dic_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila06.setObjectName("lineEdit_Dic_Fila06")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila06)
        self.lineEdit_Dic_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila07.setObjectName("lineEdit_Dic_Fila07")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.pushButton_01 = QtWidgets.QPushButton(self.subwindow)
        self.pushButton_01.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_01.setObjectName("pushButton_01")
        self.verticalLayout_15.addWidget(self.pushButton_01)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setObjectName("subwindow_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.subwindow_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label = QtWidgets.QLabel(self.subwindow_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.subwindow_2)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.subwindow_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_17.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.subwindow_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_17.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.subwindow_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_17.addWidget(self.label_27)
        self.label_30 = QtWidgets.QLabel(self.subwindow_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_17.addWidget(self.label_30)
        self.label_29 = QtWidgets.QLabel(self.subwindow_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_17.addWidget(self.label_29)
        self.label_32 = QtWidgets.QLabel(self.subwindow_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_17.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.subwindow_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_17.addWidget(self.label_31)
        self.label_34 = QtWidgets.QLabel(self.subwindow_2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_17.addWidget(self.label_34)
        self.label_33 = QtWidgets.QLabel(self.subwindow_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_17.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.subwindow_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_17.addWidget(self.label_35)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.subwindow_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_IT02_F01 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F01.setObjectName("lineEdit_IT02_F01")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F01)
        self.lineEdit_IT02_F02 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F02.setObjectName("lineEdit_IT02_F02")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F02)
        self.lineEdit_IT02_F03 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F03.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F03.setObjectName("lineEdit_IT02_F03")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F03)
        self.lineEdit_IT02_F04 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F04.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F04.setObjectName("lineEdit_IT02_F04")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F04)
        self.lineEdit_IT02_F05 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F05.setObjectName("lineEdit_IT02_F05")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F05)
        self.lineEdit_IT02_F06 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F06.setObjectName("lineEdit_IT02_F06")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F06)
        self.lineEdit_IT02_F07 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F07.setObjectName("lineEdit_IT02_F07")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F07)
        self.lineEdit_IT02_F08 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F08.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F08.setObjectName("lineEdit_IT02_F08")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F08)
        self.lineEdit_IT02_F09 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F09.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F09.setObjectName("lineEdit_IT02_F09")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F09)
        self.lineEdit_IT02_F10 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F10.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F10.setObjectName("lineEdit_IT02_F10")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F10)
        self.lineEdit_IT02_F11 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F11.setObjectName("lineEdit_IT02_F11")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F11)
        self.verticalLayout_19.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_24 = QtWidgets.QLabel(self.subwindow_2)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_21.addWidget(self.label_24)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_36 = QtWidgets.QLabel(self.subwindow_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_20.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.subwindow_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_20.addWidget(self.label_37)
        self.label_39 = QtWidgets.QLabel(self.subwindow_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.subwindow_2)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.label_41 = QtWidgets.QLabel(self.subwindow_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_20.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.subwindow_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_20.addWidget(self.label_40)
        self.label_43 = QtWidgets.QLabel(self.subwindow_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_20.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.subwindow_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_20.addWidget(self.label_42)
        self.label_45 = QtWidgets.QLabel(self.subwindow_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_20.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.subwindow_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_20.addWidget(self.label_44)
        self.label_47 = QtWidgets.QLabel(self.subwindow_2)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_20.addWidget(self.label_47)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.horizontalLayout_2.addLayout(self.verticalLayout_21)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.subwindow_2)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_22.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setObjectName("subwindow_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.subwindow_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_46 = QtWidgets.QLabel(self.subwindow_3)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_25.addWidget(self.label_46)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.subwindow_3)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_50 = QtWidgets.QLabel(self.tab_3)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_26.addWidget(self.label_50)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_26.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_26.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_26.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_26.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_26.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_26.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_26.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_26.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_26.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_26.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_26.addWidget(self.lineEdit_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_54 = QtWidgets.QLabel(self.tab_3)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_27.addWidget(self.label_54)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_27.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_27.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_27.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_27.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_27.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_27.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_27.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_27.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_27.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_27.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_27.addWidget(self.lineEdit_22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_28.addWidget(self.label_55)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_28.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_28.addWidget(self.lineEdit_24)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_28.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_28.addWidget(self.lineEdit_26)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_28.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_28.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_28.addWidget(self.lineEdit_28)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_28.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_30.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout_28.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.verticalLayout_28.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.verticalLayout_28.addWidget(self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.verticalLayout_28.addWidget(self.lineEdit_33)
        self.horizontalLayout_4.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_29.addWidget(self.label_56)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_34.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.verticalLayout_29.addWidget(self.lineEdit_34)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.verticalLayout_29.addWidget(self.lineEdit_35)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.verticalLayout_29.addWidget(self.lineEdit_36)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.verticalLayout_29.addWidget(self.lineEdit_37)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_38.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.verticalLayout_29.addWidget(self.lineEdit_38)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_39.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.verticalLayout_29.addWidget(self.lineEdit_39)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_40.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.verticalLayout_29.addWidget(self.lineEdit_40)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_41.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.verticalLayout_29.addWidget(self.lineEdit_41)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_42.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.verticalLayout_29.addWidget(self.lineEdit_42)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.verticalLayout_29.addWidget(self.lineEdit_43)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.verticalLayout_29.addWidget(self.lineEdit_44)
        self.horizontalLayout_4.addLayout(self.verticalLayout_29)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_30.addWidget(self.label_51)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_45.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.verticalLayout_30.addWidget(self.lineEdit_45)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.verticalLayout_30.addWidget(self.lineEdit_46)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_47.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.verticalLayout_30.addWidget(self.lineEdit_47)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_48.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.verticalLayout_30.addWidget(self.lineEdit_48)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_49.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.verticalLayout_30.addWidget(self.lineEdit_49)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_50.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.verticalLayout_30.addWidget(self.lineEdit_50)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_51.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.verticalLayout_30.addWidget(self.lineEdit_51)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_52.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.verticalLayout_30.addWidget(self.lineEdit_52)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_53.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.verticalLayout_30.addWidget(self.lineEdit_53)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_54.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.verticalLayout_30.addWidget(self.lineEdit_54)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_55.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.verticalLayout_30.addWidget(self.lineEdit_55)
        self.horizontalLayout_5.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_57 = QtWidgets.QLabel(self.tab_4)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_31.addWidget(self.label_57)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_56.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.verticalLayout_31.addWidget(self.lineEdit_56)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_57.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.verticalLayout_31.addWidget(self.lineEdit_57)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_58.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.verticalLayout_31.addWidget(self.lineEdit_58)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_59.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.verticalLayout_31.addWidget(self.lineEdit_59)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_60.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.verticalLayout_31.addWidget(self.lineEdit_60)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_61.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.verticalLayout_31.addWidget(self.lineEdit_61)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_62.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.verticalLayout_31.addWidget(self.lineEdit_62)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_63.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.verticalLayout_31.addWidget(self.lineEdit_63)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_64.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.verticalLayout_31.addWidget(self.lineEdit_64)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_65.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.verticalLayout_31.addWidget(self.lineEdit_65)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_66.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.verticalLayout_31.addWidget(self.lineEdit_66)
        self.horizontalLayout_5.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_58 = QtWidgets.QLabel(self.tab_4)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_32.addWidget(self.label_58)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_67.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.verticalLayout_32.addWidget(self.lineEdit_67)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_68.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.verticalLayout_32.addWidget(self.lineEdit_68)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_69.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.verticalLayout_32.addWidget(self.lineEdit_69)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_70.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.verticalLayout_32.addWidget(self.lineEdit_70)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_71.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.verticalLayout_32.addWidget(self.lineEdit_71)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_72.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.verticalLayout_32.addWidget(self.lineEdit_72)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_73.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.verticalLayout_32.addWidget(self.lineEdit_73)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_74.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.verticalLayout_32.addWidget(self.lineEdit_74)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_75.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.verticalLayout_32.addWidget(self.lineEdit_75)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_76.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.verticalLayout_32.addWidget(self.lineEdit_76)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_77.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.verticalLayout_32.addWidget(self.lineEdit_77)
        self.horizontalLayout_5.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_59 = QtWidgets.QLabel(self.tab_4)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_33.addWidget(self.label_59)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_78.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.verticalLayout_33.addWidget(self.lineEdit_78)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_79.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.verticalLayout_33.addWidget(self.lineEdit_79)
        self.lineEdit_80 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_80.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.verticalLayout_33.addWidget(self.lineEdit_80)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_81.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.verticalLayout_33.addWidget(self.lineEdit_81)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_82.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.verticalLayout_33.addWidget(self.lineEdit_82)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_83.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.verticalLayout_33.addWidget(self.lineEdit_83)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_84.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.verticalLayout_33.addWidget(self.lineEdit_84)
        self.lineEdit_85 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_85.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.verticalLayout_33.addWidget(self.lineEdit_85)
        self.lineEdit_86 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_86.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.verticalLayout_33.addWidget(self.lineEdit_86)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_87.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.verticalLayout_33.addWidget(self.lineEdit_87)
        self.lineEdit_88 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_88.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.verticalLayout_33.addWidget(self.lineEdit_88)
        self.horizontalLayout_5.addLayout(self.verticalLayout_33)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_25.addWidget(self.tabWidget_2)
        self.gridLayout_5.addLayout(self.verticalLayout_25, 0, 0, 1, 1)
        self.subwindow_4 = QtWidgets.QWidget()
        self.subwindow_4.setObjectName("subwindow_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.subwindow_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_49 = QtWidgets.QLabel(self.subwindow_4)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_24.addWidget(self.label_49)
        self.textEdit = QtWidgets.QTextEdit(self.subwindow_4)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_24.addWidget(self.textEdit)
        self.gridLayout_6.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.mdiArea)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setGeometry(QtCore.QRect(90, 60, 321, 16))
        self.label_48.setObjectName("label_48")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_23.addWidget(self.tabWidget)
        self.gridLayout_4.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 21))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSubWindow_View = QtWidgets.QAction(MainWindow)
        self.actionSubWindow_View.setObjectName("actionSubWindow_View")
        self.actionTabbed_View = QtWidgets.QAction(MainWindow)
        self.actionTabbed_View.setObjectName("actionTabbed_View")
        self.actionCascade_View = QtWidgets.QAction(MainWindow)
        self.actionCascade_View.setObjectName("actionCascade_View")
        self.actionTile_View = QtWidgets.QAction(MainWindow)
        self.actionTile_View.setObjectName("actionTile_View")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_software = QtWidgets.QAction(MainWindow)
        self.actionAbout_software.setObjectName("actionAbout_software")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.menuMen.addAction(self.actionOpen)
        self.menuMen.addAction(self.actionSave)
        self.menuWindow.addAction(self.actionSubWindow_View)
        self.menuWindow.addAction(self.actionTabbed_View)
        self.menuWindow.addAction(self.actionCascade_View)
        self.menuWindow.addAction(self.actionTile_View)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_software)
        self.menuEdition.addAction(self.actionCut)
        self.menuEdition.addAction(self.actionCopy)
        self.menuEdition.addAction(self.actionPaste)
        self.menubar.addAction(self.menuMen.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WB"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Water Balance</span></p></body></html>"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Tabla 01"))
        self.label_3.setText(_translate("MainWindow", "Month"))
        self.label_4.setText(_translate("MainWindow", "Precipitation (mm) - p"))
        self.label_5.setText(_translate("MainWindow", "SD (mm)"))
        self.label_18.setText(_translate("MainWindow", "Min Precipitation (mm)"))
        self.label_19.setText(_translate("MainWindow", "Max Precipitation (mm)"))
        self.label_20.setText(_translate("MainWindow", "Min Days - d1"))
        self.label_21.setText(_translate("MainWindow", "Max Days - d2"))
        self.label_22.setText(_translate("MainWindow", "Evaporation (mm/day) - E"))
        self.label_6.setText(_translate("MainWindow", "Jan"))
        self.label_7.setText(_translate("MainWindow", "Feb"))
        self.label_8.setText(_translate("MainWindow", "Mar"))
        self.label_9.setText(_translate("MainWindow", "Abr"))
        self.label_10.setText(_translate("MainWindow", "May"))
        self.label_11.setText(_translate("MainWindow", "Jun"))
        self.label_12.setText(_translate("MainWindow", "Jul"))
        self.label_13.setText(_translate("MainWindow", "Aug"))
        self.label_14.setText(_translate("MainWindow", "Set"))
        self.label_15.setText(_translate("MainWindow", "Oct"))
        self.label_16.setText(_translate("MainWindow", "Nov"))
        self.label_17.setText(_translate("MainWindow", "Dic"))
        self.pushButton_01.setText(_translate("MainWindow", "Clic"))
        self.subwindow_2.setWindowTitle(_translate("MainWindow", "Tabla 02"))
        self.label.setText(_translate("MainWindow", "Variable"))
        self.label_25.setText(_translate("MainWindow", "Catchment Area (m2)"))
        self.label_26.setText(_translate("MainWindow", "Pumping Rate (m3/day)"))
        self.label_28.setText(_translate("MainWindow", "Wet Deposition Runoff"))
        self.label_27.setText(_translate("MainWindow", "Dry Deposition Runoff"))
        self.label_30.setText(_translate("MainWindow", "Coefficient of Runoff"))
        self.label_29.setText(_translate("MainWindow", "Percentage solid by weight"))
        self.label_32.setText(_translate("MainWindow", "Percentage solid by weight"))
        self.label_31.setText(_translate("MainWindow", "Specific Gravity of Solids"))
        self.label_34.setText(_translate("MainWindow", "Pan Evaportaion Constant"))
        self.label_33.setText(_translate("MainWindow", "Other Water infow (m3/day)"))
        self.label_35.setText(_translate("MainWindow", "Production Rate (t/day)"))
        self.label_23.setText(_translate("MainWindow", "Value"))
        self.label_24.setText(_translate("MainWindow", "Symbol"))
        self.label_36.setText(_translate("MainWindow", "A"))
        self.label_37.setText(_translate("MainWindow", "B"))
        self.label_39.setText(_translate("MainWindow", "s1"))
        self.label_38.setText(_translate("MainWindow", "s2"))
        self.label_41.setText(_translate("MainWindow", "r"))
        self.label_40.setText(_translate("MainWindow", "%s1"))
        self.label_43.setText(_translate("MainWindow", "%s2"))
        self.label_42.setText(_translate("MainWindow", "SG"))
        self.label_45.setText(_translate("MainWindow", "e"))
        self.label_44.setText(_translate("MainWindow", "O"))
        self.label_47.setText(_translate("MainWindow", "T"))
        self.pushButton.setText(_translate("MainWindow", "Clic"))
        self.subwindow_3.setWindowTitle(_translate("MainWindow", "Tabla 03"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Stage Capacity Curves</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "Contour Elevation (m) "))
        self.label_54.setText(_translate("MainWindow", "Area (m2) - Ax"))
        self.label_55.setText(_translate("MainWindow", "Volume(m3) - Vx"))
        self.label_56.setText(_translate("MainWindow", "dam depth (m) - y"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.label_51.setText(_translate("MainWindow", "Contour Elevation (m) "))
        self.label_57.setText(_translate("MainWindow", "Area (m2) - Ax"))
        self.label_58.setText(_translate("MainWindow", "Volume(m3) - Vx"))
        self.label_59.setText(_translate("MainWindow", "dam depth (m) - y"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.subwindow_4.setWindowTitle(_translate("MainWindow", "Tabla 04"))
        self.label_49.setText(_translate("MainWindow", "Observaciones:"))
        self.pushButton_2.setText(_translate("MainWindow", "Generar reporte PDF"))
        self.pushButton_3.setText(_translate("MainWindow", "Guardar valores en un archivo TXT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "01. Inputs"))
        self.label_48.setText(_translate("MainWindow", "Este es un mensaje de prueba"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "02. Escheme"))
        self.menuMen.setTitle(_translate("MainWindow", "Home"))
        self.menuWindow.setTitle(_translate("MainWindow", "Windows"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition"))
        self.actionSubWindow_View.setText(_translate("MainWindow", "SubWindow View"))
        self.actionTabbed_View.setText(_translate("MainWindow", "Tabbed View"))
        self.actionCascade_View.setText(_translate("MainWindow", "Cascade View"))
        self.actionTile_View.setText(_translate("MainWindow", "Tile View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionAbout.setText(_translate("MainWindow", "Web of project"))
        self.actionAbout_software.setText(_translate("MainWindow", "About software"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))

