# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option03_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_23.addWidget(self.label_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mdiArea = QtWidgets.QMdiArea(self.tab)
        self.mdiArea.setMinimumSize(QtCore.QSize(200, 200))
        self.mdiArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mdiArea.setStyleSheet("background-color: rgb(0, 170, 255);")
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.gridLayout = QtWidgets.QGridLayout(self.subwindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.subwindow)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.subwindow)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.subwindow)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_18 = QtWidgets.QLabel(self.subwindow)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.subwindow)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.subwindow)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.subwindow)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.subwindow)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.subwindow)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_Jan_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila01.setObjectName("lineEdit_Jan_Fila01")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila01)
        self.lineEdit_Jan_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila02.setObjectName("lineEdit_Jan_Fila02")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila02)
        self.lineEdit_Jan_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila03.setObjectName("lineEdit_Jan_Fila03")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila03)
        self.lineEdit_Jan_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila04.setObjectName("lineEdit_Jan_Fila04")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila04)
        self.lineEdit_Jan_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila05.setObjectName("lineEdit_Jan_Fila05")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila05)
        self.lineEdit_Jan_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila06.setObjectName("lineEdit_Jan_Fila06")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila06)
        self.lineEdit_Jan_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila07.setObjectName("lineEdit_Jan_Fila07")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.subwindow)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_Feb_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila01.setObjectName("lineEdit_Feb_Fila01")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila01)
        self.lineEdit_Feb_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila02.setObjectName("lineEdit_Feb_Fila02")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila02)
        self.lineEdit_Feb_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila03.setObjectName("lineEdit_Feb_Fila03")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila03)
        self.lineEdit_Feb_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila04.setObjectName("lineEdit_Feb_Fila04")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila04)
        self.lineEdit_Feb_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila05.setObjectName("lineEdit_Feb_Fila05")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila05)
        self.lineEdit_Feb_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila06.setObjectName("lineEdit_Feb_Fila06")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila06)
        self.lineEdit_Feb_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila07.setObjectName("lineEdit_Feb_Fila07")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.subwindow)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.lineEdit_Mar_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila01.setObjectName("lineEdit_Mar_Fila01")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila01)
        self.lineEdit_Mar_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila02.setObjectName("lineEdit_Mar_Fila02")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila02)
        self.lineEdit_Mar_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila03.setObjectName("lineEdit_Mar_Fila03")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila03)
        self.lineEdit_Mar_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila04.setObjectName("lineEdit_Mar_Fila04")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila04)
        self.lineEdit_Mar_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila05.setObjectName("lineEdit_Mar_Fila05")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila05)
        self.lineEdit_Mar_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila06.setObjectName("lineEdit_Mar_Fila06")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila06)
        self.lineEdit_Mar_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila07.setObjectName("lineEdit_Mar_Fila07")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.subwindow)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_Abr_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila01.setObjectName("lineEdit_Abr_Fila01")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila01)
        self.lineEdit_Abr_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila02.setObjectName("lineEdit_Abr_Fila02")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila02)
        self.lineEdit_Abr_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila03.setObjectName("lineEdit_Abr_Fila03")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila03)
        self.lineEdit_Abr_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila04.setObjectName("lineEdit_Abr_Fila04")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila04)
        self.lineEdit_Abr_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila05.setObjectName("lineEdit_Abr_Fila05")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila05)
        self.lineEdit_Abr_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila06.setObjectName("lineEdit_Abr_Fila06")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila06)
        self.lineEdit_Abr_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila07.setObjectName("lineEdit_Abr_Fila07")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.subwindow)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEdit_May_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila01.setObjectName("lineEdit_May_Fila01")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila01)
        self.lineEdit_May_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila02.setObjectName("lineEdit_May_Fila02")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila02)
        self.lineEdit_May_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila03.setObjectName("lineEdit_May_Fila03")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila03)
        self.lineEdit_May_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila04.setObjectName("lineEdit_May_Fila04")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila04)
        self.lineEdit_May_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila05.setObjectName("lineEdit_May_Fila05")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila05)
        self.lineEdit_May_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila06.setObjectName("lineEdit_May_Fila06")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila06)
        self.lineEdit_May_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila07.setObjectName("lineEdit_May_Fila07")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.subwindow)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_Jun_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila01.setObjectName("lineEdit_Jun_Fila01")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila01)
        self.lineEdit_Jun_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila02.setObjectName("lineEdit_Jun_Fila02")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila02)
        self.lineEdit_Jun_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila03.setObjectName("lineEdit_Jun_Fila03")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila03)
        self.lineEdit_Jun_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila04.setObjectName("lineEdit_Jun_Fila04")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila04)
        self.lineEdit_Jun_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila05.setObjectName("lineEdit_Jun_Fila05")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila05)
        self.lineEdit_Jun_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila06.setObjectName("lineEdit_Jun_Fila06")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila06)
        self.lineEdit_Jun_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila07.setObjectName("lineEdit_Jun_Fila07")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.subwindow)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEdit_Jul_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila01.setObjectName("lineEdit_Jul_Fila01")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila01)
        self.lineEdit_Jul_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila02.setObjectName("lineEdit_Jul_Fila02")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila02)
        self.lineEdit_Jul_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila03.setObjectName("lineEdit_Jul_Fila03")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila03)
        self.lineEdit_Jul_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila04.setObjectName("lineEdit_Jul_Fila04")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila04)
        self.lineEdit_Jul_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila05.setObjectName("lineEdit_Jul_Fila05")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila05)
        self.lineEdit_Jul_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila06.setObjectName("lineEdit_Jul_Fila06")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila06)
        self.lineEdit_Jul_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila07.setObjectName("lineEdit_Jul_Fila07")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.subwindow)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.lineEdit_Aug_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila01.setObjectName("lineEdit_Aug_Fila01")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila01)
        self.lineEdit_Aug_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila02.setObjectName("lineEdit_Aug_Fila02")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila02)
        self.lineEdit_Aug_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila03.setObjectName("lineEdit_Aug_Fila03")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila03)
        self.lineEdit_Aug_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila04.setObjectName("lineEdit_Aug_Fila04")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila04)
        self.lineEdit_Aug_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila05.setObjectName("lineEdit_Aug_Fila05")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila05)
        self.lineEdit_Aug_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila06.setObjectName("lineEdit_Aug_Fila06")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila06)
        self.lineEdit_Aug_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila07.setObjectName("lineEdit_Aug_Fila07")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.subwindow)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.lineEdit_Set_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila01.setObjectName("lineEdit_Set_Fila01")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila01)
        self.lineEdit_Set_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila02.setObjectName("lineEdit_Set_Fila02")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila02)
        self.lineEdit_Set_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila03.setObjectName("lineEdit_Set_Fila03")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila03)
        self.lineEdit_Set_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila04.setObjectName("lineEdit_Set_Fila04")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila04)
        self.lineEdit_Set_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila05.setObjectName("lineEdit_Set_Fila05")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila05)
        self.lineEdit_Set_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila06.setObjectName("lineEdit_Set_Fila06")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila06)
        self.lineEdit_Set_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila07.setObjectName("lineEdit_Set_Fila07")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.subwindow)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.lineEdit_Oct_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila01.setObjectName("lineEdit_Oct_Fila01")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila01)
        self.lineEdit_Oct_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila02.setObjectName("lineEdit_Oct_Fila02")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila02)
        self.lineEdit_Oct_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila03.setObjectName("lineEdit_Oct_Fila03")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila03)
        self.lineEdit_Oct_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila04.setObjectName("lineEdit_Oct_Fila04")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila04)
        self.lineEdit_Oct_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila05.setObjectName("lineEdit_Oct_Fila05")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila05)
        self.lineEdit_Oct_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila06.setObjectName("lineEdit_Oct_Fila06")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila06)
        self.lineEdit_Oct_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila07.setObjectName("lineEdit_Oct_Fila07")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.subwindow)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.lineEdit_Nov_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila01.setObjectName("lineEdit_Nov_Fila01")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila01)
        self.lineEdit_Nov_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila02.setObjectName("lineEdit_Nov_Fila02")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila02)
        self.lineEdit_Nov_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila03.setObjectName("lineEdit_Nov_Fila03")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila03)
        self.lineEdit_Nov_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila04.setObjectName("lineEdit_Nov_Fila04")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila04)
        self.lineEdit_Nov_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila05.setObjectName("lineEdit_Nov_Fila05")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila05)
        self.lineEdit_Nov_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila06.setObjectName("lineEdit_Nov_Fila06")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila06)
        self.lineEdit_Nov_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila07.setObjectName("lineEdit_Nov_Fila07")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.subwindow)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.lineEdit_Dic_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila01.setObjectName("lineEdit_Dic_Fila01")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila01)
        self.lineEdit_Dic_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila02.setObjectName("lineEdit_Dic_Fila02")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila02)
        self.lineEdit_Dic_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila03.setObjectName("lineEdit_Dic_Fila03")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila03)
        self.lineEdit_Dic_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila04.setObjectName("lineEdit_Dic_Fila04")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila04)
        self.lineEdit_Dic_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila05.setObjectName("lineEdit_Dic_Fila05")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila05)
        self.lineEdit_Dic_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila06.setObjectName("lineEdit_Dic_Fila06")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila06)
        self.lineEdit_Dic_Fila07 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila07.setObjectName("lineEdit_Dic_Fila07")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila07)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.pushButton_01 = QtWidgets.QPushButton(self.subwindow)
        self.pushButton_01.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_01.setObjectName("pushButton_01")
        self.verticalLayout_15.addWidget(self.pushButton_01)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setObjectName("subwindow_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.subwindow_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label = QtWidgets.QLabel(self.subwindow_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.subwindow_2)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.subwindow_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_17.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.subwindow_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_17.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.subwindow_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_17.addWidget(self.label_27)
        self.label_30 = QtWidgets.QLabel(self.subwindow_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_17.addWidget(self.label_30)
        self.label_29 = QtWidgets.QLabel(self.subwindow_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_17.addWidget(self.label_29)
        self.label_32 = QtWidgets.QLabel(self.subwindow_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_17.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.subwindow_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_17.addWidget(self.label_31)
        self.label_34 = QtWidgets.QLabel(self.subwindow_2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_17.addWidget(self.label_34)
        self.label_33 = QtWidgets.QLabel(self.subwindow_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_17.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.subwindow_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_17.addWidget(self.label_35)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.subwindow_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_IT02_F01 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F01.setObjectName("lineEdit_IT02_F01")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F01)
        self.lineEdit_IT02_F02 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F02.setObjectName("lineEdit_IT02_F02")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F02)
        self.lineEdit_IT02_F03 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F03.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F03.setObjectName("lineEdit_IT02_F03")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F03)
        self.lineEdit_IT02_F04 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F04.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F04.setObjectName("lineEdit_IT02_F04")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F04)
        self.lineEdit_IT02_F05 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F05.setObjectName("lineEdit_IT02_F05")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F05)
        self.lineEdit_IT02_F06 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F06.setObjectName("lineEdit_IT02_F06")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F06)
        self.lineEdit_IT02_F07 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F07.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F07.setObjectName("lineEdit_IT02_F07")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F07)
        self.lineEdit_IT02_F08 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F08.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F08.setObjectName("lineEdit_IT02_F08")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F08)
        self.lineEdit_IT02_F09 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F09.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F09.setObjectName("lineEdit_IT02_F09")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F09)
        self.lineEdit_IT02_F10 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F10.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_IT02_F10.setObjectName("lineEdit_IT02_F10")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F10)
        self.lineEdit_IT02_F11 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_IT02_F11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_IT02_F11.setObjectName("lineEdit_IT02_F11")
        self.verticalLayout_16.addWidget(self.lineEdit_IT02_F11)
        self.verticalLayout_19.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_24 = QtWidgets.QLabel(self.subwindow_2)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_21.addWidget(self.label_24)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_36 = QtWidgets.QLabel(self.subwindow_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_20.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.subwindow_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_20.addWidget(self.label_37)
        self.label_39 = QtWidgets.QLabel(self.subwindow_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.subwindow_2)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.label_41 = QtWidgets.QLabel(self.subwindow_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_20.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.subwindow_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_20.addWidget(self.label_40)
        self.label_43 = QtWidgets.QLabel(self.subwindow_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_20.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.subwindow_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_20.addWidget(self.label_42)
        self.label_45 = QtWidgets.QLabel(self.subwindow_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_20.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.subwindow_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_20.addWidget(self.label_44)
        self.label_47 = QtWidgets.QLabel(self.subwindow_2)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_20.addWidget(self.label_47)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.horizontalLayout_2.addLayout(self.verticalLayout_21)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.subwindow_2)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_22.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setObjectName("subwindow_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.subwindow_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_46 = QtWidgets.QLabel(self.subwindow_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 0, 0, 1, 1)
        self.subwindow_4 = QtWidgets.QWidget()
        self.subwindow_4.setObjectName("subwindow_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.subwindow_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_49 = QtWidgets.QLabel(self.subwindow_4)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_24.addWidget(self.label_49)
        self.textEdit = QtWidgets.QTextEdit(self.subwindow_4)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_24.addWidget(self.textEdit)
        self.gridLayout_6.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.mdiArea)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setGeometry(QtCore.QRect(90, 60, 321, 16))
        self.label_48.setObjectName("label_48")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_23.addWidget(self.tabWidget)
        self.gridLayout_4.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 21))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSubWindow_View = QtWidgets.QAction(MainWindow)
        self.actionSubWindow_View.setObjectName("actionSubWindow_View")
        self.actionTabbed_View = QtWidgets.QAction(MainWindow)
        self.actionTabbed_View.setObjectName("actionTabbed_View")
        self.actionCascade_View = QtWidgets.QAction(MainWindow)
        self.actionCascade_View.setObjectName("actionCascade_View")
        self.actionTile_View = QtWidgets.QAction(MainWindow)
        self.actionTile_View.setObjectName("actionTile_View")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_software = QtWidgets.QAction(MainWindow)
        self.actionAbout_software.setObjectName("actionAbout_software")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.menuMen.addAction(self.actionOpen)
        self.menuMen.addAction(self.actionSave)
        self.menuWindow.addAction(self.actionSubWindow_View)
        self.menuWindow.addAction(self.actionTabbed_View)
        self.menuWindow.addAction(self.actionCascade_View)
        self.menuWindow.addAction(self.actionTile_View)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_software)
        self.menuEdition.addAction(self.actionCut)
        self.menuEdition.addAction(self.actionCopy)
        self.menuEdition.addAction(self.actionPaste)
        self.menubar.addAction(self.menuMen.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WB"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Water Balance</span></p></body></html>"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Tabla 01"))
        self.label_3.setText(_translate("MainWindow", "Month"))
        self.label_4.setText(_translate("MainWindow", "Precipitation (mm) - p"))
        self.label_5.setText(_translate("MainWindow", "SD (mm)"))
        self.label_18.setText(_translate("MainWindow", "Min Precipitation (mm)"))
        self.label_19.setText(_translate("MainWindow", "Max Precipitation (mm)"))
        self.label_20.setText(_translate("MainWindow", "Min Days - d1"))
        self.label_21.setText(_translate("MainWindow", "Max Days - d2"))
        self.label_22.setText(_translate("MainWindow", "Evaporation (mm/day) - E"))
        self.label_6.setText(_translate("MainWindow", "Jan"))
        self.label_7.setText(_translate("MainWindow", "Feb"))
        self.label_8.setText(_translate("MainWindow", "Mar"))
        self.label_9.setText(_translate("MainWindow", "Abr"))
        self.label_10.setText(_translate("MainWindow", "May"))
        self.label_11.setText(_translate("MainWindow", "Jun"))
        self.label_12.setText(_translate("MainWindow", "Jul"))
        self.label_13.setText(_translate("MainWindow", "Aug"))
        self.label_14.setText(_translate("MainWindow", "Set"))
        self.label_15.setText(_translate("MainWindow", "Oct"))
        self.label_16.setText(_translate("MainWindow", "Nov"))
        self.label_17.setText(_translate("MainWindow", "Dic"))
        self.pushButton_01.setText(_translate("MainWindow", "Clic"))
        self.subwindow_2.setWindowTitle(_translate("MainWindow", "Tabla 02"))
        self.label.setText(_translate("MainWindow", "Variable"))
        self.label_25.setText(_translate("MainWindow", "Catchment Area (m2)"))
        self.label_26.setText(_translate("MainWindow", "Pumping Rate (m3/day)"))
        self.label_28.setText(_translate("MainWindow", "Wet Deposition Runoff"))
        self.label_27.setText(_translate("MainWindow", "Dry Deposition Runoff"))
        self.label_30.setText(_translate("MainWindow", "Coefficient of Runoff"))
        self.label_29.setText(_translate("MainWindow", "Percentage solid by weight"))
        self.label_32.setText(_translate("MainWindow", "Percentage solid by weight"))
        self.label_31.setText(_translate("MainWindow", "Specific Gravity of Solids"))
        self.label_34.setText(_translate("MainWindow", "Pan Evaportaion Constant"))
        self.label_33.setText(_translate("MainWindow", "Other Water infow (m3/day)"))
        self.label_35.setText(_translate("MainWindow", "Production Rate (t/day)"))
        self.label_23.setText(_translate("MainWindow", "Value"))
        self.label_24.setText(_translate("MainWindow", "Symbol"))
        self.label_36.setText(_translate("MainWindow", "A"))
        self.label_37.setText(_translate("MainWindow", "B"))
        self.label_39.setText(_translate("MainWindow", "s1"))
        self.label_38.setText(_translate("MainWindow", "s2"))
        self.label_41.setText(_translate("MainWindow", "r"))
        self.label_40.setText(_translate("MainWindow", "%s1"))
        self.label_43.setText(_translate("MainWindow", "%s2"))
        self.label_42.setText(_translate("MainWindow", "SG"))
        self.label_45.setText(_translate("MainWindow", "e"))
        self.label_44.setText(_translate("MainWindow", "O"))
        self.label_47.setText(_translate("MainWindow", "T"))
        self.pushButton.setText(_translate("MainWindow", "Clic"))
        self.subwindow_3.setWindowTitle(_translate("MainWindow", "Tabla 03"))
        self.label_46.setText(_translate("MainWindow", "Contour Elevation (m) "))
        self.subwindow_4.setWindowTitle(_translate("MainWindow", "Tabla 04"))
        self.label_49.setText(_translate("MainWindow", "Observaciones:"))
        self.pushButton_2.setText(_translate("MainWindow", "Generar reporte PDF"))
        self.pushButton_3.setText(_translate("MainWindow", "Guardar valores en un archivo TXT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "01. Inputs"))
        self.label_48.setText(_translate("MainWindow", "Este es un mensaje de prueba"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "02. Escheme"))
        self.menuMen.setTitle(_translate("MainWindow", "Home"))
        self.menuWindow.setTitle(_translate("MainWindow", "Windows"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition"))
        self.actionSubWindow_View.setText(_translate("MainWindow", "SubWindow View"))
        self.actionTabbed_View.setText(_translate("MainWindow", "Tabbed View"))
        self.actionCascade_View.setText(_translate("MainWindow", "Cascade View"))
        self.actionTile_View.setText(_translate("MainWindow", "Tile View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionAbout.setText(_translate("MainWindow", "Web of project"))
        self.actionAbout_software.setText(_translate("MainWindow", "About software"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))

