# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option01.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(989, 533)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mdiArea = QtWidgets.QMdiArea(self.tab)
        self.mdiArea.setMinimumSize(QtCore.QSize(200, 200))
        self.mdiArea.setStyleSheet("background-color: rgb(0, 170, 255);")
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.gridLayout = QtWidgets.QGridLayout(self.subwindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.subwindow)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.subwindow)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.subwindow)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_18 = QtWidgets.QLabel(self.subwindow)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.subwindow)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.subwindow)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.subwindow)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.subwindow)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.subwindow)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_Jan_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila01.setObjectName("lineEdit_Jan_Fila01")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila01)
        self.lineEdit_Jan_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila02.setObjectName("lineEdit_Jan_Fila02")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila02)
        self.lineEdit_Jan_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila03.setObjectName("lineEdit_Jan_Fila03")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila03)
        self.lineEdit_Jan_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jan_Fila04.setObjectName("lineEdit_Jan_Fila04")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila04)
        self.lineEdit_Jan_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila05.setObjectName("lineEdit_Jan_Fila05")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila05)
        self.lineEdit_Jan_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jan_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jan_Fila06.setObjectName("lineEdit_Jan_Fila06")
        self.verticalLayout_2.addWidget(self.lineEdit_Jan_Fila06)
        self.lineEdit = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.subwindow)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_Feb_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila01.setObjectName("lineEdit_Feb_Fila01")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila01)
        self.lineEdit_Feb_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila02.setObjectName("lineEdit_Feb_Fila02")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila02)
        self.lineEdit_Feb_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila03.setObjectName("lineEdit_Feb_Fila03")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila03)
        self.lineEdit_Feb_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Feb_Fila04.setObjectName("lineEdit_Feb_Fila04")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila04)
        self.lineEdit_Feb_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila05.setObjectName("lineEdit_Feb_Fila05")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila05)
        self.lineEdit_Feb_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Feb_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Feb_Fila06.setObjectName("lineEdit_Feb_Fila06")
        self.verticalLayout_3.addWidget(self.lineEdit_Feb_Fila06)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.subwindow)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.lineEdit_Mar_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila01.setObjectName("lineEdit_Mar_Fila01")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila01)
        self.lineEdit_Mar_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila02.setObjectName("lineEdit_Mar_Fila02")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila02)
        self.lineEdit_Mar_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila03.setObjectName("lineEdit_Mar_Fila03")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila03)
        self.lineEdit_Mar_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Mar_Fila04.setObjectName("lineEdit_Mar_Fila04")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila04)
        self.lineEdit_Mar_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila05.setObjectName("lineEdit_Mar_Fila05")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila05)
        self.lineEdit_Mar_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Mar_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Mar_Fila06.setObjectName("lineEdit_Mar_Fila06")
        self.verticalLayout_4.addWidget(self.lineEdit_Mar_Fila06)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.subwindow)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_Abr_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila01.setObjectName("lineEdit_Abr_Fila01")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila01)
        self.lineEdit_Abr_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila02.setObjectName("lineEdit_Abr_Fila02")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila02)
        self.lineEdit_Abr_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila03.setObjectName("lineEdit_Abr_Fila03")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila03)
        self.lineEdit_Abr_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Abr_Fila04.setObjectName("lineEdit_Abr_Fila04")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila04)
        self.lineEdit_Abr_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila05.setObjectName("lineEdit_Abr_Fila05")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila05)
        self.lineEdit_Abr_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Abr_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Abr_Fila06.setObjectName("lineEdit_Abr_Fila06")
        self.verticalLayout_5.addWidget(self.lineEdit_Abr_Fila06)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.subwindow)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEdit_May_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila01.setObjectName("lineEdit_May_Fila01")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila01)
        self.lineEdit_May_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila02.setObjectName("lineEdit_May_Fila02")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila02)
        self.lineEdit_May_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila03.setObjectName("lineEdit_May_Fila03")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila03)
        self.lineEdit_May_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_May_Fila04.setObjectName("lineEdit_May_Fila04")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila04)
        self.lineEdit_May_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila05.setObjectName("lineEdit_May_Fila05")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila05)
        self.lineEdit_May_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_May_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_May_Fila06.setObjectName("lineEdit_May_Fila06")
        self.verticalLayout_7.addWidget(self.lineEdit_May_Fila06)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_7.addWidget(self.lineEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.subwindow)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_Jun_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila01.setObjectName("lineEdit_Jun_Fila01")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila01)
        self.lineEdit_Jun_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila02.setObjectName("lineEdit_Jun_Fila02")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila02)
        self.lineEdit_Jun_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila03.setObjectName("lineEdit_Jun_Fila03")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila03)
        self.lineEdit_Jun_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jun_Fila04.setObjectName("lineEdit_Jun_Fila04")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila04)
        self.lineEdit_Jun_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila05.setObjectName("lineEdit_Jun_Fila05")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila05)
        self.lineEdit_Jun_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jun_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jun_Fila06.setObjectName("lineEdit_Jun_Fila06")
        self.verticalLayout_8.addWidget(self.lineEdit_Jun_Fila06)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_8.addWidget(self.lineEdit_7)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.subwindow)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEdit_Jul_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila01.setObjectName("lineEdit_Jul_Fila01")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila01)
        self.lineEdit_Jul_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila02.setObjectName("lineEdit_Jul_Fila02")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila02)
        self.lineEdit_Jul_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila03.setObjectName("lineEdit_Jul_Fila03")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila03)
        self.lineEdit_Jul_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Jul_Fila04.setObjectName("lineEdit_Jul_Fila04")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila04)
        self.lineEdit_Jul_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila05.setObjectName("lineEdit_Jul_Fila05")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila05)
        self.lineEdit_Jul_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Jul_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Jul_Fila06.setObjectName("lineEdit_Jul_Fila06")
        self.verticalLayout_9.addWidget(self.lineEdit_Jul_Fila06)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_9.addWidget(self.lineEdit_8)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.subwindow)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.lineEdit_Aug_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila01.setObjectName("lineEdit_Aug_Fila01")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila01)
        self.lineEdit_Aug_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila02.setObjectName("lineEdit_Aug_Fila02")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila02)
        self.lineEdit_Aug_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila03.setObjectName("lineEdit_Aug_Fila03")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila03)
        self.lineEdit_Aug_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Aug_Fila04.setObjectName("lineEdit_Aug_Fila04")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila04)
        self.lineEdit_Aug_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila05.setObjectName("lineEdit_Aug_Fila05")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila05)
        self.lineEdit_Aug_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Aug_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Aug_Fila06.setObjectName("lineEdit_Aug_Fila06")
        self.verticalLayout_10.addWidget(self.lineEdit_Aug_Fila06)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_10.addWidget(self.lineEdit_9)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.subwindow)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.lineEdit_Set_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila01.setObjectName("lineEdit_Set_Fila01")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila01)
        self.lineEdit_Set_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila02.setObjectName("lineEdit_Set_Fila02")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila02)
        self.lineEdit_Set_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila03.setObjectName("lineEdit_Set_Fila03")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila03)
        self.lineEdit_Set_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Set_Fila04.setObjectName("lineEdit_Set_Fila04")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila04)
        self.lineEdit_Set_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila05.setObjectName("lineEdit_Set_Fila05")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila05)
        self.lineEdit_Set_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Set_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Set_Fila06.setObjectName("lineEdit_Set_Fila06")
        self.verticalLayout_11.addWidget(self.lineEdit_Set_Fila06)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_11.addWidget(self.lineEdit_6)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.subwindow)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.lineEdit_Oct_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila01.setObjectName("lineEdit_Oct_Fila01")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila01)
        self.lineEdit_Oct_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila02.setObjectName("lineEdit_Oct_Fila02")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila02)
        self.lineEdit_Oct_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila03.setObjectName("lineEdit_Oct_Fila03")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila03)
        self.lineEdit_Oct_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Oct_Fila04.setObjectName("lineEdit_Oct_Fila04")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila04)
        self.lineEdit_Oct_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila05.setObjectName("lineEdit_Oct_Fila05")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila05)
        self.lineEdit_Oct_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Oct_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Oct_Fila06.setObjectName("lineEdit_Oct_Fila06")
        self.verticalLayout_12.addWidget(self.lineEdit_Oct_Fila06)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_12.addWidget(self.lineEdit_11)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.subwindow)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.lineEdit_Nov_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila01.setObjectName("lineEdit_Nov_Fila01")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila01)
        self.lineEdit_Nov_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila02.setObjectName("lineEdit_Nov_Fila02")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila02)
        self.lineEdit_Nov_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila03.setObjectName("lineEdit_Nov_Fila03")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila03)
        self.lineEdit_Nov_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Nov_Fila04.setObjectName("lineEdit_Nov_Fila04")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila04)
        self.lineEdit_Nov_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila05.setObjectName("lineEdit_Nov_Fila05")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila05)
        self.lineEdit_Nov_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Nov_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nov_Fila06.setObjectName("lineEdit_Nov_Fila06")
        self.verticalLayout_13.addWidget(self.lineEdit_Nov_Fila06)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_13.addWidget(self.lineEdit_12)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.subwindow)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.lineEdit_Dic_Fila01 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila01.setObjectName("lineEdit_Dic_Fila01")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila01)
        self.lineEdit_Dic_Fila02 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila02.setObjectName("lineEdit_Dic_Fila02")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila02)
        self.lineEdit_Dic_Fila03 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila03.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila03.setObjectName("lineEdit_Dic_Fila03")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila03)
        self.lineEdit_Dic_Fila04 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila04.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_Dic_Fila04.setObjectName("lineEdit_Dic_Fila04")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila04)
        self.lineEdit_Dic_Fila05 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila05.setObjectName("lineEdit_Dic_Fila05")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila05)
        self.lineEdit_Dic_Fila06 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_Dic_Fila06.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Dic_Fila06.setObjectName("lineEdit_Dic_Fila06")
        self.verticalLayout_14.addWidget(self.lineEdit_Dic_Fila06)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.subwindow)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_14.addWidget(self.lineEdit_10)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.pushButton_01 = QtWidgets.QPushButton(self.subwindow)
        self.pushButton_01.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_01.setObjectName("pushButton_01")
        self.verticalLayout_15.addWidget(self.pushButton_01)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setObjectName("subwindow_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.subwindow_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label = QtWidgets.QLabel(self.subwindow_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.subwindow_2)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.subwindow_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_17.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.subwindow_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_17.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.subwindow_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_17.addWidget(self.label_27)
        self.label_30 = QtWidgets.QLabel(self.subwindow_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_17.addWidget(self.label_30)
        self.label_29 = QtWidgets.QLabel(self.subwindow_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_17.addWidget(self.label_29)
        self.label_32 = QtWidgets.QLabel(self.subwindow_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_17.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.subwindow_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_17.addWidget(self.label_31)
        self.label_34 = QtWidgets.QLabel(self.subwindow_2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_17.addWidget(self.label_34)
        self.label_33 = QtWidgets.QLabel(self.subwindow_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_17.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.subwindow_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_17.addWidget(self.label_35)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.subwindow_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_16.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_16.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_16.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_16.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_16.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_16.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_16.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_16.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_21.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_16.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_16.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.subwindow_2)
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_16.addWidget(self.lineEdit_23)
        self.verticalLayout_19.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_24 = QtWidgets.QLabel(self.subwindow_2)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_21.addWidget(self.label_24)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_36 = QtWidgets.QLabel(self.subwindow_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_20.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.subwindow_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_20.addWidget(self.label_37)
        self.label_39 = QtWidgets.QLabel(self.subwindow_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.subwindow_2)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.label_41 = QtWidgets.QLabel(self.subwindow_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_20.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.subwindow_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_20.addWidget(self.label_40)
        self.label_43 = QtWidgets.QLabel(self.subwindow_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_20.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.subwindow_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_20.addWidget(self.label_42)
        self.label_45 = QtWidgets.QLabel(self.subwindow_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_20.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.subwindow_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_20.addWidget(self.label_44)
        self.label_47 = QtWidgets.QLabel(self.subwindow_2)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_20.addWidget(self.label_47)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.horizontalLayout_2.addLayout(self.verticalLayout_21)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.subwindow_2)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_22.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setObjectName("subwindow_3")
        self.verticalLayout_6.addWidget(self.mdiArea)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_6.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WB"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Water Balance</span></p></body></html>"))
        self.subwindow.setWindowTitle(_translate("Dialog", "Tabla 01"))
        self.label_3.setText(_translate("Dialog", "Month"))
        self.label_4.setText(_translate("Dialog", "Precipitation (mm) - p"))
        self.label_5.setText(_translate("Dialog", "SD (mm)"))
        self.label_18.setText(_translate("Dialog", "Min Precipitation (mm)"))
        self.label_19.setText(_translate("Dialog", "Max Precipitation (mm)"))
        self.label_20.setText(_translate("Dialog", "Min Days - d1"))
        self.label_21.setText(_translate("Dialog", "Max Days - d2"))
        self.label_22.setText(_translate("Dialog", "Evaporation (mm/day) - E"))
        self.label_6.setText(_translate("Dialog", "Jan"))
        self.label_7.setText(_translate("Dialog", "Feb"))
        self.label_8.setText(_translate("Dialog", "Mar"))
        self.label_9.setText(_translate("Dialog", "Abr"))
        self.label_10.setText(_translate("Dialog", "May"))
        self.label_11.setText(_translate("Dialog", "Jun"))
        self.label_12.setText(_translate("Dialog", "Jul"))
        self.label_13.setText(_translate("Dialog", "Aug"))
        self.label_14.setText(_translate("Dialog", "Set"))
        self.label_15.setText(_translate("Dialog", "Oct"))
        self.label_16.setText(_translate("Dialog", "Nov"))
        self.label_17.setText(_translate("Dialog", "Dic"))
        self.pushButton_01.setText(_translate("Dialog", "Clic"))
        self.subwindow_2.setWindowTitle(_translate("Dialog", "Tabla 02"))
        self.label.setText(_translate("Dialog", "Variable"))
        self.label_25.setText(_translate("Dialog", "Catchment Area (m2)"))
        self.label_26.setText(_translate("Dialog", "Pumping Rate (m3/day)"))
        self.label_28.setText(_translate("Dialog", "Wet Deposition Runoff"))
        self.label_27.setText(_translate("Dialog", "Dry Deposition Runoff"))
        self.label_30.setText(_translate("Dialog", "Coefficient of Runoff"))
        self.label_29.setText(_translate("Dialog", "Percentage solid by weight"))
        self.label_32.setText(_translate("Dialog", "Percentage solid by weight"))
        self.label_31.setText(_translate("Dialog", "Specific Gravity of Solids"))
        self.label_34.setText(_translate("Dialog", "Pan Evaportaion Constant"))
        self.label_33.setText(_translate("Dialog", "Other Water infow (m3/day)"))
        self.label_35.setText(_translate("Dialog", "Production Rate (t/day)"))
        self.label_23.setText(_translate("Dialog", "Value"))
        self.label_24.setText(_translate("Dialog", "Symbol"))
        self.label_36.setText(_translate("Dialog", "A"))
        self.label_37.setText(_translate("Dialog", "B"))
        self.label_39.setText(_translate("Dialog", "s1"))
        self.label_38.setText(_translate("Dialog", "s2"))
        self.label_41.setText(_translate("Dialog", "r"))
        self.label_40.setText(_translate("Dialog", "%s1"))
        self.label_43.setText(_translate("Dialog", "%s2"))
        self.label_42.setText(_translate("Dialog", "SG"))
        self.label_45.setText(_translate("Dialog", "e"))
        self.label_44.setText(_translate("Dialog", "O"))
        self.label_47.setText(_translate("Dialog", "T"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.subwindow_3.setWindowTitle(_translate("Dialog", "Subwindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Inputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Escheme"))

